### ISSUE TITLE
Image Inversion

### ISSUE THREAD

**Issue by jvgonzalvo** [hugrubsan/Offline-Handwriting-Recognition-with-TensorFlow#4]
I read the code in hw_utils.py that inverts and scales the image. Why is it needed to invert the image?

**Comment by hugrubsan** [comment]
The main reason is the maxpool layers.

When parsing the input image to a tensor, it is necessary that the elements corresponding to the parts "written" in the image have a higher value than the "unwritten" parts. 

Original image:
![image](https://user-images.githubusercontent.com/29400925/36661200-fe09e344-1ada-11e8-912a-37fa443263b9.png)

Processed image:
![image](https://user-images.githubusercontent.com/29400925/36661301-2ff8215e-1adb-11e8-94d4-d6856bdb4981.png)
