### ISSUE TITLE
Prediction Outputs

### ISSUE THREAD

**Issue by jvgonzalvo** [hugrubsan/Offline-Handwriting-Recognition-with-TensorFlow#7]
I noticed that the output layer you used for your architecture is a ctc decoder. If I recall correctly, the outputs generated by these decoders is a `SparseTensor`. How do you get the predicted characters from there without using converting them into dense tensors through `sparse_to_dense`?

**Comment by hugrubsan** [comment]
This decoding is only implemented in "test.py" and is done word by word using a dictionary that contains the correspondences between labels (as integers) and characters. 
Exactly in these lines:
```
dec=session.run(decoded[0],test_feed) 
output = str(list(map(dct.get, list(dec.values))))
```

**Comment by jvgonzalvo** [comment]
I guess you just need the values property of the `SparseTensor` generated by the decoder and nothing else?

**Comment by hugrubsan** [comment]
Yes, I just need those values.
