### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by jvgonzalvo** [hugrubsan/Offline-Handwriting-Recognition-with-TensorFlow#8]
I tried using the architecture you have for my own project and unfortunately, I am unable to reproduce the results. Would you mind you uploading the model that performs well? I would like to use it for the mobile app I'm working on?

**Comment by hugrubsan** [comment]
This is the model that performs well, something you will be doing wrong... Do you run training, validation and test IAM or evaluate the model with cross-validation?

You can use the model for whatever you want, I'm with other projects and this is finished.

**Comment by jvgonzalvo** [comment]
My apologies for the lots of questions. What I meant by “model” is the
weights file.

**Comment by hugrubsan** [comment]
I dont have it, this project is actually a final degree project and I delivered it a long time ago... sorry.

**Comment by jvgonzalvo** [comment]
It’s alright. I’ll try to reproduce the results myself. I thank you for
entertaining my queries.
